a1 = [[rand();rand()]]
a2 = [[rand();rand()]]
a3 = [[rand();rand()]]
a4 = [[rand();rand()]]
a5 = [[rand();rand()]]
a6 = [[rand();rand()]]
a7 = [[rand();rand()]]
a8 = [[rand();rand()]]
b1 = [a1 a2 a3 a4]
b2 = [a5 a6 a7 a8]
c = [b1; b2]
findmax(c)